services:
  feather-rank:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: feather-rank:prod
    env_file:
      - path: .env
        required: false
    environment:
      # Production settings - explicitly set to avoid test mode
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      TEST_MODE: "0"
      EPHEMERAL_DB: "0"
      DATABASE_PATH: "/data/smashcord_prod.sqlite"
      # DISCORD_TOKEN will be loaded from .env file if it exists
    volumes:
      # Bind mount to view persistent data at ./data on the host
      - ./data:/data
    # Default command is declared in the Dockerfile (./run_prod.sh runs app.py)
    restart: unless-stopped
